name: buttons_tabbar
description: A Flutter package that implements a TabBar where each label is a toggle button.
version: 0.1.1+1
homepage: https://github.com/Afonsocraposo
repository: https://github.com/Afonsocraposo/buttons_tabbar

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
